#@TYPE: Machine
#@NAME: Cavium Small Form Factor Reference CN7000 evb 64bit
#@DESCRIPTION: sff-ref-cn71xx-64

DEFAULTTUNE = "octeon3_64"
require conf/machine/include/octeon3.inc


PREFERRED_VERSION_linux-yocto-lts = "4.14%"
PREFERRED_PROVIDER_virtual/kernel = "linux-octeon-lts"

#PREFERRED_VERSION_linux-yocto = "6.6%"
#PREFERRED_PROVIDER_virtual/kernel = "linux-yocto"

IMAGE_BOOT_FILES += " \
    vmlinux.64;vmlinux.64 \
"

IMAGE_FSTYPES += "wic"

WKS_FILE = "octeon-sff7000.wks"

OLDEST_KERNEL:sff-ref-cn71xx-64 = "4.14"

MACHINE_FEATURES_BACKFILL_CONSIDERED:sff-ref-cn71xx-64:append = " qemu-usermode"