# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "octeon"
BBFILE_PATTERN_octeon = "^${LAYERDIR}/"
BBFILE_PRIORITY_octeon = "6"

LAYERVERSION_octeon = "4"
LAYERSERIES_COMPAT_octeon = "scarthgap"